# -*- coding: utf-8 -*-
"""Catboost &Adaboost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVntpH3kImRCckWNS_OA6dqrsjKRkHD7
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('/content/Titanic-Dataset.csv')

df.head()

df.info()

df.shape

df.describe()

df.isnull().sum()

df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df = df.drop(['Cabin'], axis = 1)
df.head()

df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})

df['Embarked'] = df['Embarked'].map({'C':0, 'Q':1, 'S':2})

df['FamilySize'] = df['SibSp'] + df['Parch'] + 1

df.drop(['Name','Ticket','PassengerId'] , axis = 1, inplace = True)

df.info()

df['Age'] = df['Age'].fillna(df['Age'].median())

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

model = LogisticRegression(max_iter=1000, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Logistic Regression Accuracy:", accuracy)

pip install catboost pandas scikit-learn

from catboost import CatBoostClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

target = 'Survived'
X = df.drop(target, axis=1)
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

cat_model = CatBoostClassifier(
    iterations=100,
    learning_rate=0.1,
    depth=6,
    verbose=0
)

cat_model.fit(X_train, y_train)

cat_pred = cat_model.predict(X_test)

cat_accuracy = accuracy_score(y_test, cat_pred)

print("\nCatBoost Accuracy:", cat_accuracy)

ada_model = AdaBoostClassifier(
    n_estimators=100,
    learning_rate=1.0,
    random_state=42
)

ada_model.fit(X_train, y_train)
ada_pred = ada_model.predict(X_test)

ada_accuracy = accuracy_score(y_test, ada_pred)
print("\nAdaBoost Accuracy:", ada_accuracy)

