# -*- coding: utf-8 -*-
"""DBSCAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sXAEpbH-3-t_NXf6qJhCP-Hl8UWsYVb2
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
# %matplotlib inline

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("/content/Mall_Customers (1).csv")

df.head()

df.info()

df.describe()

df.shape

df.isnull().sum()

df.drop(['CustomerID','Gender','Age'],axis=1,inplace=True)

df.head()

print('Annual Income',df['Annual Income (k$)'].unique())
print('Spending Score',df['Spending Score (1-100)'].unique())

sns.countplot(data=df, x='Annual Income (k$)')

sns.countplot(data=df, x='Spending Score (1-100)')

df.isnull().sum().sum()

df.corr()

sns.pairplot(data=df)

plt.scatter(df['Annual Income (k$)'],df['Spending Score (1-100)'])
plt.show()

scaler=StandardScaler()
scaler.fit(df)
scaler_train=scaler.transform(df)

from sklearn.metrics import v_measure_score
from sklearn.cluster import DBSCAN

dbscan_cluster = DBSCAN(eps=0.5,min_samples=15)
dbscan_cluster.fit(scaler_train)
print('labels: ',np.unique(dbscan_cluster.labels_))

plt.scatter(scaler_train[:, 0],
scaler_train[:, 1],
c=dbscan_cluster.labels_,
label=scaler_train)
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")

labels=dbscan_cluster.labels_
N_clus=len(set(labels))-(1 if -1 in labels else 0)
print('Estimated no. of clusters: %d' % N_clus)

n_noise = list(dbscan_cluster.labels_).count(-1)
print('Estimated no. of noise points: %d' % n_noise)

from sklearn.metrics import silhouette_score
print('score: ',silhouette_score(scaler_train,dbscan_cluster.labels_))

from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score

best_score = -1

for eps in [0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]:
    for ms in [3,4,5,6,7,8]:
        db = DBSCAN(eps=eps, min_samples=ms)
        labels = db.fit_predict(scaler_train)

        if len(set(labels)) > 1 and len(set(labels)) != 1:
            try:
                score = silhouette_score(scaler_train, labels)
                print(eps, ms, round(score,3))

                if score > best_score:
                    best_score = score
                    best_eps = eps
                    best_ms = ms
            except:
                pass

print("Best Score:", best_score)
print("Best eps:", best_eps)
print("Best min_samples:", best_ms)

