# -*- coding: utf-8 -*-
"""DecisionTree .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FP_q7r7OfK8gzG9nu1L6dFDCMGcLGOXf
"""

import pandas as pd
from google.colab import files
upload=files.upload()

df = pd.read_csv("/content/data.csv")
df.head()

df.info()

df.describe()

df.shape

df.isnull().sum()

df = df.drop_duplicates()
if 'Unnamed: 32' in df.columns:
    df.drop('Unnamed: 32', axis=1, inplace=True)
if 'id' in df.columns:
    df.drop('id', axis=1, inplace=True)
df['diagnosis'] = df['diagnosis'].map({'M':1,'B':0})
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns

sns.countplot(x='diagnosis', data=df)
plt.title("Diagnosis Count")
plt.show()

df.hist(figsize=(15,12))
plt.tight_layout()
plt.show()

plt.pie(df['diagnosis'].value_counts())
plt.title("Diagnosis Distribution")
plt.show()

plt.figure(figsize=(12,10))
sns.heatmap(df.corr(), cmap='coolwarm')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X = df.drop('diagnosis', axis=1)
y = df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(
    X,y,test_size=0.2,random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

cart = DecisionTreeClassifier(
    criterion='gini',
    random_state=42)

cart.fit(X_train,y_train)
pred_cart = cart.predict(X_test)
print("CART Accuracy:",accuracy_score(y_test,pred_cart))
print(confusion_matrix(y_test,pred_cart))
print(classification_report(y_test,pred_cart))

id3 = DecisionTreeClassifier(
    criterion='entropy',
    random_state=42)
id3.fit(X_train,y_train)
pred_id3 = id3.predict(X_test)
print("ID3 Accuracy:",accuracy_score(y_test,pred_id3))
print(confusion_matrix(y_test,pred_id3))
print(classification_report(y_test,pred_id3))

c45 = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=5,
    min_samples_split=5,
    random_state=42)
c45.fit(X_train,y_train)
pred_c45 = c45.predict(X_test)
print("C4.5 Accuracy:",accuracy_score(y_test,pred_c45))
print(confusion_matrix(y_test,pred_c45))
print(classification_report(y_test,pred_c45))

models = ['CART','ID3','C4.5']
acc = [
accuracy_score(y_test,pred_cart),
accuracy_score(y_test,pred_id3),
accuracy_score(y_test,pred_c45)
]
plt.bar(models,acc)
plt.ylim(0.8,1.0)
plt.ylabel("Accuracy")
plt.title("Model Comparison")
plt.show()

