# -*- coding: utf-8 -*-
"""Extra Tree&Isolation_Forest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YV8UCa4zvhm66QN5GKuz4IpKUeAiWP2B
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("/content/creditcard.csv")

df.head()

df.shape

df.info()

df.describe()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

features = ['V14', 'V17', 'V12', 'Amount']

X = df[features]
y = df['Class']

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score

model = ExtraTreesClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy :", accuracy*100)

from sklearn.ensemble import IsolationForest
from sklearn.metrics import classification_report

iso = IsolationForest(
    contamination=0.0017,
    random_state=42
)

iso.fit(X_train)

pred = iso.predict(X_test)

pred = [1 if x==-1 else 0 for x in pred]

print(classification_report(y_test,pred))

v14 = float(input("Enter V14: "))
v17 = float(input("Enter V17: "))
v12 = float(input("Enter V12: "))
amount = float(input("Enter Amount: "))

new_data = [[v14, v17, v12, amount]]

new_data = scaler.transform(new_data)

prediction = model.predict(new_data)

if prediction[0] == 0:
    print("Normal Transaction")
else:
    print("Fraud Transaction")

