# -*- coding: utf-8 -*-
"""Gradient Boosting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Y9FNWtqiP4bNgwxXwFDzoj8Wcwc-4kk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files

uploaded=files.upload()

df=pd.read_csv('/content/data.csv')

df.head()

df.tail()

df.info()

df.shape

df.isnull().sum()

df.drop(['Unnamed: 32'],axis=1,inplace=True)

counts = df['diagnosis'].value_counts()
plt.figure()
plt.bar(counts.index, counts.values)
plt.title("Bar Chart - Breast Cancer Class Distribution")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

plt.figure()
plt.pie(counts.values, labels=counts.index, startangle=90)
plt.title("Pie Chart - Breast Cancer Percentage Distribution")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

X = df.drop('diagnosis', axis=1)
y = df['diagnosis']

if y.dtype == 'object':
    y = LabelEncoder().fit_transform(y)

scaler = StandardScaler()
X = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

model = GradientBoostingClassifier(n_estimators=200,learning_rate=0.05,max_depth=3,random_state=42)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

