# -*- coding: utf-8 -*-
"""KNN practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bV98Dt2Jw8c8EGNqYIPR2ecUFAmDMx75
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('/content/data.csv')

df.head()

df.info()

df.describe()

df.shape

if 'id' in df.columns:
    df.drop('id', axis=1, inplace=True)

df['diagnosis'] = df['diagnosis'].map({'M':1,'B':0})

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X = df.drop(['diagnosis', 'Unnamed: 32'], axis=1)
y = df['diagnosis']

X.dropna(inplace=True)
y = y.loc[X.index]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

