# -*- coding: utf-8 -*-
"""L1 ,L2,Elastic_Net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xifAI3zImR9fvnQnDG5AhXd9ug-pnrie
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

from google.colab import files
uploaded=files.upload()

dataset=pd.read_csv('/content/mtcars.csv')

dataset.head()

dataset.info()

dataset.describe()

dataset.isnull().sum()

X=dataset.drop("mpg",axis=1)
y=dataset["mpg"]

from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_X_numeric = scaler.fit_transform(train_X_numeric)
test_X_numeric = scaler.transform(test_X_numeric)

from sklearn.linear_model import LinearRegression
reg = LinearRegression()
train_X_numeric = train_X.drop('model', axis=1)
test_X_numeric = test_X.drop('model', axis=1)
reg.fit(train_X_numeric, train_y)

reg.score(train_X_numeric, train_y)

reg.score(test_X_numeric, test_y)

from sklearn.linear_model import Lasso
lasso_reg = Lasso(alpha=0.01)
lasso_reg.fit(train_X_numeric, train_y)

lasso_reg.score(train_X_numeric, train_y)

lasso_reg.score(test_X_numeric, test_y)

from sklearn.linear_model import Ridge
ridge_reg = Ridge(alpha=0.1)
ridge_reg.fit(train_X_numeric, train_y)

ridge_reg.score(train_X_numeric, train_y)

ridge_reg.score(test_X_numeric, test_y)

from sklearn.linear_model import ElasticNet
elastic_reg = ElasticNet(alpha=0.01, l1_ratio=0.5)
elastic_reg.fit(train_X_numeric, train_y)

elastic_reg.score(train_X_numeric, train_y)

elastic_reg.score(test_X_numeric, test_y)

