# -*- coding: utf-8 -*-
"""lgbm&rf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yqAI7-OpZs0Fk5GHRisDRWVUuItO1rqY
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("bank.csv")

df.head()

df.info()

df = df.drop_duplicates()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for col in df.select_dtypes(include="object").columns:
    df[col] = le.fit_transform(df[col])

X = df.drop("deposit", axis=1)
y = df["deposit"]

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from lightgbm import LGBMClassifier

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

"""**LIGHT GBM**"""

model = LGBMClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=5,
    random_state=42
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", (accuracy_score(y_test, y_pred) * 100), "%")

"""RANDOM FOREST

"""

from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Accuracy:", round(accuracy_score(y_test, rf_pred) * 100, 2), "%")

