# -*- coding: utf-8 -*-
"""linear intercept.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HSKflPwjUCOL1B4WJ6UKnvVe2P-iPPCn
"""

import numpy as np
import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

from google.colab import files
uploaded=files.upload()

df=pd.read_csv("/content/canada_per_capita_income.csv")

df.head()

df.describe()

df.info()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
plt.xlabel('year')
plt.ylabel('per capita income')
plt.scatter(df.year,df['per capita income (US$)'],color='red',marker='+')

new_df=df.drop('per capita income (US$)',axis='columns')
new_df

price=df['per capita income (US$)']
price

reg = linear_model.LinearRegression()
reg.fit(new_df,price)

reg.predict([[2020]])

reg.intercept_

