# -*- coding: utf-8 -*-
"""Logistic Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1ljC7-c5c8mYKIiu8inHu9Vnp1DDx6C
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from google.colab import files
uploaded=files.upload()

dataset = pd.read_csv('/content/HR_comma_sep.csv')
dataset.head()

pd.crosstab(dataset.salary, dataset.left).plot(kind='bar')
plt.xlabel("Salary")
plt.ylabel("Employee Count")
plt.title("Salary vs Employee Retention")
plt.show()

pd.crosstab(dataset.Department, dataset.left).plot(kind='bar', figsize=(10,5))
plt.xlabel("Department")
plt.ylabel("Employee Count")
plt.title("Department vs Employee Retention")
plt.show()

subdata = dataset[['satisfaction_level',
                   'average_montly_hours',
                   'promotion_last_5years',
                   'salary']]

salary_dummies = pd.get_dummies(subdata.salary, prefix='salary')
salary_dummies = salary_dummies.astype(int)

data = pd.concat([subdata, salary_dummies], axis=1)
data.drop('salary', axis=1, inplace=True)
data.head()

X = data
y = dataset.left

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy :", accuracy)
print("Accuracy Percentage :", accuracy*100)

