# -*- coding: utf-8 -*-
"""Polynomial Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LA8m1UniEVyloVYfJQIb3oUpduojIsi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

from google.colab import files
uploaded=files.upload()

dataset = pd.read_csv("kc_house_data.csv")

dataset.head()

X = dataset[['bedrooms','bathrooms','sqft_living','floors','waterfront','view','condition','grade','sqft_above','sqft_basement','yr_built','yr_renovated','lat','long','sqft_living15']]

y = dataset['price']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

poly = PolynomialFeatures(degree=2,include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

linearReg = LinearRegression()
linearReg.fit(X_train_poly, y_train)

y_predict = linearReg.predict(X_test_poly)

accuracy = r2_score(y_test, y_predict)
print("R2 Score :", accuracy)
print("Accuracy :", accuracy*100,"%")

new_house_features = [3,2,1800,1,0,0,7,dataset['grade'].mean(),dataset['sqft_above'].mean(),dataset['sqft_basement'].mean(),dataset['yr_built'].mean(),dataset['yr_renovated'].mean(),dataset['lat'].mean(),dataset['long'].mean(),dataset['sqft_living15'].mean() ]
new_house_df = pd.DataFrame([new_house_features], columns=X.columns)

new_house_poly = poly.transform(new_house_df)
prediction = linearReg.predict(new_house_poly)
print("Predicted House Price :", prediction[0])

