# -*- coding: utf-8 -*-
"""Practice  Lasso.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DO5Nt1QWEu1p8L7-nIpdTY1ynzTCxuTA
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('/content/Sample - Superstore.csv', encoding='latin1')

df.head()

df.info()

df.describe()

df.isnull().sum()

df = df.drop([
'Row ID',
'Order ID',
'Customer ID',
'Customer Name',
'Product ID',
'Product Name',
'Country'
],axis=1)

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df["Order Month"] = df["Order Date"].dt.month
df["Order Year"] = df["Order Date"].dt.year

df["Shipping Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

df = df.drop(["Order Date","Ship Date"],axis=1)

df = pd.get_dummies(df, drop_first=True)

new_df = df.drop(['Profit'],axis=1)
profit= df['Profit']

numeric_cols = new_df.select_dtypes(include=['number']).columns

X= new_df[numeric_cols]
y = profit

from sklearn.model_selection import train_test_split

train_X,test_X,train_y,test_y=train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

train_X = scaler.fit_transform(train_X)
test_X = scaler.transform(test_X)

from sklearn.linear_model import Lasso

model = Lasso(alpha=0.001, max_iter=10000)

model.fit(train_X, train_y)

print("Training Score :", model.score(train_X, train_y))
print("Testing Score :", model.score(test_X, test_y))

pred = model.predict(test_X)

from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

print("R2 Score :", r2_score(test_y, pred))
print("MAE :", mean_absolute_error(test_y, pred))
print("MSE :", mean_squared_error(test_y, pred))
print("RMSE :", np.sqrt(mean_squared_error(test_y, pred)))

import pandas as pd

sample_input_data = pd.DataFrame([[42420, 3000, 2, 0.0, 11, 2016, 3]],
                                 columns=['Postal Code', 'Sales', 'Quantity', 'Discount',
                                          'Order Month', 'Order Year', 'Shipping Days'])

scaled_sample_input = scaler.transform(sample_input_data)
predicted_profit = model.predict(scaled_sample_input)[0]
print(f"Predicted Profit: {predicted_profit:.2f}")

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))

plt.scatter(test_y, pred, color='blue')

plt.plot([test_y.min(), test_y.max()],
         [test_y.min(), test_y.max()],
         color='red', linewidth=2)

plt.title("Actual vs Predicted Profit")
plt.xlabel("Actual Profit")
plt.ylabel("Predicted Profit")

plt.grid(True)
plt.show()

