# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pb528nCQvDy1pa-5VoSBYse1t9t3zGP2
"""

import numpy as np
import pandas as pd

from google.colab import files
uploaded=files.upload()

df=pd.read_csv('/content/StudentsPerformance.csv')

df.head()

df.describe()

df.info()

df.shape

df["Average"] = (df["math score"] +
                 df["reading score"] +
                 df["writing score"]) / 3

def grade(avg):
    if avg >= 85:
        return "A"
    elif avg >= 60:
        return "B"
    else:
        return "C"

df["Grade"] = df["Average"].apply(grade)

X = df[["math score", "reading score", "writing score"]]
y = df["Grade"]

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.svm import SVC

model = SVC(kernel="rbf", random_state=42)

model.fit(X_train, y_train)

import matplotlib.pyplot as plt

colors = {
    "A": "green",
    "B": "blue",
    "C": "red"
}

plt.figure(figsize=(8,5))

for grade in colors:
    data = df[df["Grade"] == grade]
    plt.scatter(
        data.index,
        data["Average"],
        color=colors[grade],
        label=grade,
        s=60
    )

plt.title("Student Grade Classification")
plt.xlabel("Student Index")
plt.ylabel("Average Score")
plt.legend(title="Grades")
plt.grid(True)

plt.show()

math = float(input("Enter Math Score: "))
reading = float(input("Enter Reading Score: "))
writing = float(input("Enter Writing Score: "))

new_student = [[math, reading, writing]]
new_student_scaled = scaler.transform(new_student)

prediction = model.predict(new_student_scaled)
predicted_grade = le.inverse_transform(prediction)[0]

print("Predicted Grade:", predicted_grade)

average = (math + reading + writing) / 3

filtered_df = df[df["Grade"] == predicted_grade]

plt.figure(figsize=(8,5))

plt.scatter(
    filtered_df.index,
    filtered_df["Average"],
    color="blue",
    s=60,
    label=f"{predicted_grade} Students"
)

plt.scatter(
    len(filtered_df),
    average,
    color="red",
    marker="*",
    s=250,
    label="Your Score"
)

plt.text(
    len(filtered_df),
    average + 1,
    predicted_grade,
    fontsize=12
)

plt.title(f"SVM Prediction - {predicted_grade} Category")
plt.xlabel("Students")
plt.ylabel("Average Score")
plt.legend(loc="lower right")
plt.grid(True)

plt.show()

