# -*- coding: utf-8 -*-
"""XG Boost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C6YxlqpbDSiIWqLCnHSVFBoJkKLhlMiS
"""

!pip install xgboost
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from xgboost import XGBClassifier

from google.colab import files
uploaded=files.upload()

dataset=pd.read_csv('/content/data.csv')
dataset.head()

dataset = dataset.drop(['id', 'Unnamed: 32'], axis=1)

dataset['diagnosis'] = dataset['diagnosis'].map({'M':1, 'B':0})

X = dataset.drop('diagnosis', axis=1)
y = dataset['diagnosis']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

model = XGBClassifier(n_estimators=200,learning_rate=0.05,max_depth=4,random_state=42,eval_metric='logloss')
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy :", accuracy)
print("Accuracy Percentage :", accuracy*100)

print(confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

